import { StyleSheet } from 'react-native';
import { COLORS, DESIGN_TOKENS } from '../../constants/colors';
import { responsiveFontSize, responsivePadding } from '../../utils/responsiveUtils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background.page,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: responsivePadding.horizontal(24),
    paddingTop: DESIGN_TOKENS.spacing.sm,
    paddingBottom: DESIGN_TOKENS.spacing.xxl,
  },
  title: {
    fontFamily: 'Lato_700Bold',
    fontSize: responsiveFontSize.title(24),
    fontWeight: '700',
    lineHeight: 33.6,
    letterSpacing: -0.5,
    color: COLORS.text.primary,
    marginBottom: DESIGN_TOKENS.spacing.xs,
  },
  subtitle: {
    fontFamily: 'Lato_400Regular',
    fontSize: responsiveFontSize.small(12),
    fontWeight: '400',
    lineHeight: 16.8,
    letterSpacing: 0,
    color: COLORS.text.secondary,
    marginTop: DESIGN_TOKENS.spacing.xs,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: COLORS.background.primary,
    ...DESIGN_TOKENS.shadow.md,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  avatarPlaceholder: {
    backgroundColor: COLORS.submit,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarPlaceholderText: {
    color: COLORS.text.inverse,
    fontSize: DESIGN_TOKENS.fontSize.md,
    fontWeight: 'bold',
  },
  weatherSection: {
    marginBottom: DESIGN_TOKENS.spacing.lg,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: responsivePadding.horizontal(24),
    marginBottom: DESIGN_TOKENS.spacing.lg,
    zIndex: 20,
  },
  listTitle: {
    fontFamily: 'Lato_700Bold',
    fontSize: responsiveFontSize.cardTitle(18),
    fontWeight: '600',
    lineHeight: 25.2,
    letterSpacing: 0,
    color: COLORS.text.primary,
  },
  count: {
    fontFamily: 'Lato_400Regular',
    fontSize: responsiveFontSize.small(12),
    fontWeight: '400',
    lineHeight: 16.8,
    letterSpacing: 0,
    color: COLORS.text.tertiary,
  },
  filterButton: {
    padding: DESIGN_TOKENS.spacing.sm,
    borderRadius: DESIGN_TOKENS.borderRadius.small,
    backgroundColor: COLORS.background.primary,
    ...DESIGN_TOKENS.shadow.sm,
  },
  filterButtonActive: {
    backgroundColor: COLORS.background.page,
  },
  filterBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    zIndex: 998,
  },
  filterDropdown: {
    position: 'absolute',
    width: 130,
    backgroundColor: COLORS.background.primary,
    borderRadius: DESIGN_TOKENS.borderRadius.large,
    ...DESIGN_TOKENS.shadow.xl,
    paddingVertical: DESIGN_TOKENS.spacing.sm,
    borderWidth: 1,
    borderColor: COLORS.gray[100],
    zIndex: 999,
  },
  filterOption: {
    paddingHorizontal: DESIGN_TOKENS.spacing.xl,
    paddingVertical: 14,
    backgroundColor: COLORS.background.primary,
  },
  filterOptionActive: {
    backgroundColor: COLORS.background.page,
  },
  filterOptionText: {
    fontFamily: 'Lato_400Regular',
    fontSize: DESIGN_TOKENS.fontSize.base,
    fontWeight: '500',
    lineHeight: 21,
    letterSpacing: 0,
    color: COLORS.text.secondary,
    textAlign: 'center',
  },
  filterOptionTextActive: {
    fontFamily: 'Lato_700Bold',
    fontWeight: '700',
    color: COLORS.submit,
  },
  flashListContent: {
    paddingHorizontal: DESIGN_TOKENS.spacing.sm,
    paddingBottom: DESIGN_TOKENS.spacing.xxl,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 80,
    paddingHorizontal: responsivePadding.horizontal(24),
  },
  emptyIconContainer: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: COLORS.background.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: DESIGN_TOKENS.spacing.xxl,
  },
  emptyTitle: {
    fontFamily: 'Lato_700Bold',
    fontSize: responsiveFontSize.cardTitle(18),
    fontWeight: '700',
    lineHeight: 25.2,
    letterSpacing: 0,
    color: COLORS.text.primary,
    marginBottom: DESIGN_TOKENS.spacing.sm,
    textAlign: 'center',
  },
  emptyText: {
    fontFamily: 'Lato_400Regular',
    fontSize: responsiveFontSize.body(14),
    fontWeight: '400',
    lineHeight: 20,
    letterSpacing: 0,
    color: COLORS.text.secondary,
    textAlign: 'center',
    marginBottom: DESIGN_TOKENS.spacing.xxxl,
  },
  emptyButton: {
    backgroundColor: COLORS.submit,
    paddingHorizontal: DESIGN_TOKENS.spacing.xxl,
    paddingVertical: DESIGN_TOKENS.spacing.md,
    borderRadius: DESIGN_TOKENS.borderRadius.medium,
    ...DESIGN_TOKENS.shadow.lg,
  },
  emptyButtonText: {
    fontFamily: 'Lato_700Bold',
    fontSize: DESIGN_TOKENS.fontSize.md,
    fontWeight: '700',
    color: COLORS.text.inverse,
  },
});
